import { SAFE_ID, badRequest, forward, notFound, type WorkerProxy } from "../worker-forward";

type WorkScopeRouteContext = { params: Promise<{ path?: string[] }> };

/** A subject key is generated by the worker ("ticket:jira:AWP-235") and
 *  bounded at 400 characters; control characters never belong in one. */
const SUBJECT_KEY = /^\P{Cc}{1,400}$/u;
const CURSOR = /^[A-Za-z0-9_.:=-]{1,200}$/;
const WHOLE_NUMBER = /^(?:0|[1-9][0-9]{0,9})$/;

function valid(name: string, value: string): boolean {
  if (name === "subjectKey") return SUBJECT_KEY.test(value);
  if (name === "limit" || name === "trailLimit" || name === "trailBefore") return WHOLE_NUMBER.test(value);
  if (name === "rounds") return value === "true" || value === "false";
  return CURSOR.test(value);
}

/**
 * `GET /api/work-scope[/rounds/{roundId}/deliveries|effects]`: a subject's
 * repository record with its repository questions as rounds, and each round's
 * deliveries and effects, forwarded to the worker's `/api/v1/work-scope`.
 * Rounds come only when `rounds=true` asks for them: the worker leaves them
 * out by default so callers from before they existed are unchanged.
 */
export async function handleWorkScopeGet(
  request: Request,
  { params }: WorkScopeRouteContext,
  workerProxy: WorkerProxy,
) {
  const { path = [] } = await params;
  let allowed: readonly string[];
  if (path.length === 0) {
    allowed = ["subjectKey", "rounds", "roundsCursor", "trailLimit", "trailBefore"];
  } else if (
    path.length === 3 &&
    path[0] === "rounds" &&
    SAFE_ID.test(path[1]!) &&
    (path[2] === "deliveries" || path[2] === "effects")
  ) {
    allowed = ["subjectKey", "cursor", "limit"];
  } else {
    return notFound();
  }
  const searchParams = new URL(request.url).searchParams;
  if (!searchParams.get("subjectKey")) return badRequest("subjectKey is required");
  const query = new URLSearchParams();
  for (const name of allowed) {
    const value = searchParams.get(name);
    if (value === null || value === "") continue;
    if (!valid(name, value)) return badRequest(`${name} is not a value this route takes`);
    query.set(name, value);
  }
  const suffix = path.map(encodeURIComponent).join("/");
  return forward(workerProxy, `/api/v1/work-scope${suffix ? `/${suffix}` : ""}?${query.toString()}`);
}
