export {
  BUILTIN_HARNESS_PROFILE_IDS,
  BUILTIN_HARNESS_PROFILE_MANIFESTS,
  DEFAULT_BUILTIN_HARNESS_PROFILE_ID,
  defaultBuiltinHarnessProfile,
  CALL_LLM_DEFAULT_MODEL,
  CANARY_FIXTURE_MODELS,
  CODE_HYGIENE_DEFAULT_MODEL,
  DEFAULT_MODELS,
  REPO_MEMORY_DISTILL_MODEL_CODEX,
  builtinHarnessProfileReference,
  recognised,
  resolveModelDefaults,
  resolveBuiltinHarnessProfile,
  selectable,
  type ModelProviderContract,
} from "./model-catalog";
