DELETE FROM "settings"
WHERE "key" IN (
  'POLL_INTERVAL_MS',
  'GITHUB_BASE_BRANCH',
  'GITLAB_BASE_BRANCH',
  'TRIGGER_RATE_LIMIT_MAX',
  'TRIGGER_RATE_LIMIT_WINDOW',
  'ENABLE_REVIEW_PHASE',
  'ENABLE_LEAK_REVIEW',
  'catalog.activated'
);
